module.exports = {
  env: {
    browser: true,
    es6: true,
    jest: true,
    node: true,
  },
  parser: "babel-eslint",
  extends: ["airbnb", "prettier", "prettier/react"],
  globals: {
    Atomics: "readonly",
    SharedArrayBuffer: "readonly",
  },
  parserOptions: {
    ecmaFeatures: {
      jsx: true,
      modules: true,
    },
    ecmaVersion: 2018,
    sourceType: "module",
  },
  plugins: ["react", "jsx-a11y", "import", "prettier", "jest"],
  rules: {
    // React Rules
    "prettier/prettier": "error",
    "react/forbid-prop-types": [0, { forbid: ["any"] }],
    "react/jsx-filename-extension": [
      "error",
      {
        extensions: [".js", ".jsx", ".ts", ".tsx"],
      },
    ],
    indent: 1,
    "react/no-multi-comp": "off",
    "react/destructuring-assignment": 1,
    "react/prefer-stateless-function": 1,
    "react/jsx-one-expression-per-line": 0,
    "react/prop-types": 0,
    "react-hooks/rules-of-hooks": "error", // Checks rules of Hooks
    "react-hooks/exhaustive-deps": "warn", // Checks effect dependencies
    "react/jsx-fragments": 0,
    "react/jsx-curly-newline": 0,
    "react/jsx-indent": 2,
    "react/jsx-wrap-multilines": [1, { prop: "ignore" }],
    "react/no-danger": 0,
    "react/jsx-props-no-spreading": [
      1,
      {
        custom: "ignore",
      },
    ],
    "jsx-quotes": [2, "prefer-double"],
    "jsx-a11y/anchor-is-valid": "off",
    "jsx-a11y/accessible-emoji": 0,
    "jsx-a11y/label-has-associated-control": 0,
    "react/jsx-no-bind": [
      2,
      {
        ignoreDOMComponents: false,
        ignoreRefs: true,
        allowArrowFunctions: true,
        allowFunctions: false,
        allowBind: false,
      },
    ],
    "arrow-parens": 0,
    quotes: [2, "double", { allowTemplateLiterals: true }],
    "object-curly-newline": 0,
    "wrap-iife": ["error", "inside"],
    "no-unused-vars": ["error", { args: "none" }],
    "jsx-a11y/label-has-for": "off",
    "no-new": "warn",
    "global-require": "off",
    "import-order": 0,
    "import/prefer-default-export": 1,
    "import/no-extraneous-dependencies": "off",
    "import/extensions": "off",
    "import/no-unresolved": "off",
    "no-underscore-dangle": 0,
    "prefer-promise-reject-errors": "error",
    "no-nested-ternary": "error",
    "comma-dangle": 0,
    "prefer-destructuring": 1,
    "implicit-arrow-linebreak": 0,
    "no-use-before-define": 0,
    "operator-linebreak": 0,
    "no-console": ["warn", { allow: ["warn", "info", "error"] }],
    "no-confusing-arrow": 0,
    "function-paren-newline": 0,
    "no-restricted-syntax": 1,
  },
};
